
num1 = 3
num2 = 0
try:
    resultado = (num1/num2)
    print(resultado)
except:
    print("Ha habido un error")


